name: Staff
version: '1.0-SNAPSHOT'
main: com.reflexian.staff.Staff
api-version: 1.19
dependencies:
  - name: PlaceholderAPI
    required: true
    bootstrap: false
  - name: ItemsAdder
    required: false
    bootstrap: false
  - name: LiteBans
    required: true
    bootstrap: false
authors: [Raymond]
website: reflexian.com
loader: com.reflexian.staff.StaffPluginLoader